#! /bin/sh

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width        4
bspc config window_gap          8
bspc config split_ratio         0.50
bspc config auto_alternate      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
