#! /bin/sh

bspc config border_width        2
bspc config window_gap          15

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

bspc config -d focused_border_color        "#bb9584"
bspc config -d normal_border_color         "#645240"

bspc monitor -d I II III IV V VI VII VIII IX X
